version: '{build}'
skip_tags: true
image: Visual Studio 2019
install:
build_script:
  - ps: ./Build.ps1
test: off
artifacts:
  - path: artifacts/Seq.App.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: WwOCJf+zR8dGUpTOdT6SD3wW3ZzIBzK1Tl67IaJ4TICAohn0RD11Y36aH/cOr0Hb
    skip_symbols: true
    on:
      branch: /^(master|dev)$/