version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
artifacts:
  - path: artifacts/Seq.App.*.nupkg
build_script:
  - ps: ./Build.ps1
deploy:
- provider: NuGet
  api_key:
    secure: Fj/cw/L8FDXnCHjIJEQJ1FHea0WDYYdO7XQvZcHwD+7SUQK39iRLYw8PcIHh8pkS
  skip_symbols: false
  on:
    branch: master